services:
  matterbridge:
    container_name: matterbridge
    image: luligu/matterbridge:latest # Matterbridge image with the latest tag
    network_mode: host # Ensures the Matter mdns works
    restart: always # Ensures the container always restarts automatically
    volumes:
      - ${HOME}/Matterbridge:/root/Matterbridge 
      - ${HOME}/.matterbridge:/root/.matterbridge
