services:
  matterbridge-node:
    image: vsc-matterbridge-node:latest
    build:
      context: ../..
      dockerfile: .devcontainer/node/Dockerfile
      args:
        DEVCONTAINER_VARIANT: node
    container_name: matterbridge-node-dev-container
    volumes:
      - ../..:/workspaces/matterbridge:cached
    networks:
      - matterbridge
    command: sleep infinity

networks:
  matterbridge:
    external: true
    name: matterbridge
