FROM node:20-alpine as base
WORKDIR /app


FROM base as builder
WORKDIR /app
COPY ./package.json ./
COPY ./tsconfig.json ./
COPY ./src ./src
COPY ./frontend/build ./frontend/build
RUN npm install && npm run build && npm link


FROM base as release
WORKDIR /app
COPY --from=builder /app/package.json ./
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/frontend/build ./frontend/build
RUN npm link


WORKDIR /app
CMD ["node", "dist/cli.js", "-bridge", "-docker", "-frontend", "8283", "-port", "5550"]
