# ─────────────── BUILD STAGE ───────────────
FROM node:24-trixie-slim AS builder

# 🛠️ Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

# Install git to clone the repositories
RUN apt-get update && apt-get install -y --no-install-recommends git 

WORKDIR /matterbridge
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && \
  npm run buildProduction && \
  npm pkg delete devDependencies scripts workspaces && \
  rm -rf node_modules package-lock.json npm-shrinkwrap.json && \
  npm install --no-fund --no-audit --omit=dev && \
  npm link --no-fund --no-audit && \
  npm shrinkwrap --omit=dev && \
  npm pack

WORKDIR /matterbridge-zigbee2mqtt
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-zigbee2mqtt.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-somfy-tahoma
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-somfy-tahoma.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-shelly
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-shelly.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-hass
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-hass.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-webhooks
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-webhooks.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-test
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-test.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-example-accessory-platform
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-example-accessory-platform.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-example-dynamic-platform
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-example-dynamic-platform.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-door
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-door.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-motion
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-motion.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-energy
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-energy.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-room
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-room.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-weather
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-weather.git . && \
  SHA7=$(git rev-parse --short=7 HEAD) && \
  BASE_VERSION=$(node -p "require('./package.json').version.split('-')[0]") && \
  npm pkg set version="${BASE_VERSION}-git-${SHA7}"
RUN npm ci --no-fund --no-audit && npm link matterbridge --no-fund --no-audit && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf node_modules package-lock.json npm-shrinkwrap.json && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

# ─────────────── RUNTIME STAGE ───────────────
FROM node:24-trixie-slim AS release

# 🛠️ Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /matterbridge

COPY --from=builder \
  /matterbridge/*.tgz \
  /matterbridge-zigbee2mqtt/*.tgz \
  /matterbridge-somfy-tahoma/*.tgz \
  /matterbridge-shelly/*.tgz \
  /matterbridge-hass/*.tgz \
  /matterbridge-webhooks/*.tgz \
  /matterbridge-test/*.tgz \
  /matterbridge-example-accessory-platform/*.tgz \
  /matterbridge-example-dynamic-platform/*.tgz \
  /matterbridge-eve-door/*.tgz \
  /matterbridge-eve-motion/*.tgz \
  /matterbridge-eve-energy/*.tgz \
  /matterbridge-eve-room/*.tgz \
  /matterbridge-eve-weather/*.tgz \
  ./

RUN apt-get update && \
  apt-get install -y --no-install-recommends curl && \
  apt-get clean && \
  npm install -g --no-fund --no-audit --omit=dev *.tgz && \
  npm uninstall -g corepack && \
  npm cache clean --force && \
  rm *.tgz && \
  rm -rf /tmp/* /var/tmp/* /root/.npm /root/.cache /var/lib/apt/lists/* && \
  find /usr/local/lib/node_modules -type d -name ".github" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules -type d -name ".vscode" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules -type d -name "docs" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules -type f \( -name "*.ts" -o -name "*.js.map" -o -name "*.d.ts" -o -name "*.d.ts.map" -o -name "LICENSE" -o -name "LICENSE.txt" -o -name "*.md" \) -delete && \
  find /usr/local/lib/node_modules/matterbridge/node_modules/@matter -type d -name "src" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules/matterbridge/node_modules/@matter -type d -name "cjs" -exec rm -rf {} +

# Add Docker HEALTHCHECK
HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=5 \
  CMD curl --fail http://localhost:8283/health || exit 1

# Copy and execute the entrypoint script
COPY ./docker/entrypoint.dev.sh ./
RUN chmod +x ./entrypoint.dev.sh
ENTRYPOINT ["./entrypoint.dev.sh"]
CMD ["matterbridge", "-docker"]
# ─────────────── END ───────────────
