FROM node:22-bookworm-slim
WORKDIR /app    
COPY ./docker/shellyEntrypoint.sh ./
RUN chmod +x ./shellyEntrypoint.sh && \
    npm install -g npm@latest && \
    npm install -g matterbridge && \
    npm install -g matterbridge-shelly && \
    node -v && \
    npm -v && \
    npm list -g
ENTRYPOINT ["./shellyEntrypoint.sh"]
CMD ["matterbridge", "-docker"]
