# ─────────────── BUILD STAGE ───────────────
FROM ubuntu:latest AS base

# 🛠️ Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

# Install node from NodeSource
RUN apt update && \
  apt install -y --no-install-recommends ca-certificates curl && \
  curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
  apt install -y --no-install-recommends nodejs

# Build Matterbridge for production
WORKDIR /matterbridge
COPY ./package*.json ./tsconfig*.json ./.npmignore ./
COPY ./src ./src
COPY ./frontend/package.json ./frontend/package.json
COPY ./frontend/build ./frontend/build
COPY ./bin ./bin

COPY ./packages/mb-lib-test/package*.json ./packages/mb-lib-test/tsconfig*.json ./packages/mb-lib-test/.npmignore ./packages/mb-lib-test/
COPY ./packages/mb-lib-test/src ./packages/mb-lib-test/src

RUN npm ci --no-fund --no-audit && \
  npm run cleanBuildProduction && \
  npm pkg delete devDependencies scripts types && \
  rm -rf ./node_modules && \
  npm install --no-fund --no-audit --omit=dev && \
  npm shrinkwrap --omit=dev && \
  npm pack

# ─────────────── RUNTIME STAGE ───────────────
FROM ubuntu:latest AS release

# 🛠️ Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

# Install node from NodeSource
RUN apt update && \
  apt install -y --no-install-recommends ca-certificates curl && \
  curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
  apt install -y --no-install-recommends nodejs && \
  apt update && apt upgrade -y && \
  apt purge -y apt-transport-https gnupg && \
  apt autoremove -y && \
  apt clean && \
  rm -rf /var/lib/apt/lists/*

# Install matterbridge
WORKDIR /matterbridge    
COPY --from=base /matterbridge/*.tgz .
RUN npm install *.tgz --global --verbose --no-fund --no-audit --omit=dev && rm *.tgz

# Add Docker HEALTHCHECK
HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=5 \
  CMD curl --fail http://localhost:8283/health || exit 1

# Copy and execute the entrypoint script
COPY ./docker/entrypoint.sh ./
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
CMD ["matterbridge", "-docker"]
