# ─────────────── BUILD STAGE ───────────────
FROM node:22-bookworm-slim AS builder

# 🛠️ Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

# Install git to clone the repositories
RUN apt-get update && \
  apt-get install -y --no-install-recommends \
  git 

WORKDIR /app
COPY ./package*.json ./tsconfig*.json ./.npmignore ./
COPY ./src ./src
COPY ./frontend/package.json ./frontend/package.json
COPY ./frontend/build ./frontend/build
COPY ./bin ./bin

COPY ./packages/dgram/package*.json ./packages/dgram/tsconfig*.json ./packages/dgram/.npmignore ./packages/dgram/
COPY ./packages/dgram/src ./packages/dgram/src

COPY ./packages/jest-utils/package*.json ./packages/jest-utils/tsconfig*.json ./packages/jest-utils/.npmignore ./packages/jest-utils/
COPY ./packages/jest-utils/src ./packages/jest-utils/src

COPY ./packages/utils/package*.json ./packages/utils/tsconfig*.json ./packages/utils/.npmignore ./packages/utils/
COPY ./packages/utils/src ./packages/utils/src

COPY ./packages/vitest-utils/package*.json ./packages/vitest-utils/tsconfig*.json ./packages/vitest-utils/.npmignore ./packages/vitest-utils/
COPY ./packages/vitest-utils/src ./packages/vitest-utils/src

# COPY ./vendor ./vendor

RUN npm ci --no-fund --no-audit && \
  npm run buildProduction && \
  npm pkg delete devDependencies scripts workspaces && \
  rm -rf node_modules package-lock.json npm-shrinkwrap.json && \
  npm install --no-fund --no-audit --omit=dev && \
  npm link --no-fund --no-audit && \
  npm shrinkwrap --omit=dev && \
  npm pack

WORKDIR /matterbridge-zigbee2mqtt
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-zigbee2mqtt.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-somfy-tahoma
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-somfy-tahoma.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack
WORKDIR /matterbridge-shelly
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-shelly.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-hass
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-hass.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack
WORKDIR /matterbridge-webhooks
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags -b dev https://github.com/Luligu/matterbridge-webhooks.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-test
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-test.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-example-accessory-platform
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-example-accessory-platform.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-example-dynamic-platform
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-example-dynamic-platform.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-door
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-door.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-motion
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-motion.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-energy
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-energy.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-room
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-room.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

WORKDIR /matterbridge-eve-weather
RUN GIT_SSL_NO_VERIFY=true git clone --depth 1 --single-branch --no-tags https://github.com/Luligu/matterbridge-eve-weather.git .
RUN npm ci --no-fund --no-audit && npm link matterbridge && npm run buildProduction && npm pkg delete devDependencies scripts && rm -rf ./node_modules && npm install --no-fund --no-audit --omit=dev && npm shrinkwrap && npm pack

# ─────────────── RUNTIME STAGE ───────────────
FROM node:22-bookworm-slim AS release

# 🛠️ Set noninteractive frontend
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /matterbridge

COPY --from=builder \
  /app/*.tgz \
  /matterbridge-zigbee2mqtt/*.tgz \
  /matterbridge-somfy-tahoma/*.tgz \
  /matterbridge-shelly/*.tgz \
  /matterbridge-hass/*.tgz \
  /matterbridge-webhooks/*.tgz \
  /matterbridge-test/*.tgz \
  /matterbridge-example-accessory-platform/*.tgz \
  /matterbridge-example-dynamic-platform/*.tgz \
  /matterbridge-eve-door/*.tgz \
  /matterbridge-eve-motion/*.tgz \
  /matterbridge-eve-energy/*.tgz \
  /matterbridge-eve-room/*.tgz \
  /matterbridge-eve-weather/*.tgz \
  ./

RUN apt-get update && \
  apt-get install -y --no-install-recommends curl && \
  apt-get clean && \
  npm install -g --no-fund --no-audit --omit=dev *.tgz && \
  npm uninstall -g corepack && \
  npm cache clean --force && \
  rm *.tgz && \
  rm -rf /tmp/* /var/tmp/* /root/.npm /root/.cache /var/lib/apt/lists/* && \
  find /usr/local/lib/node_modules -type d -name ".github" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules -type d -name ".vscode" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules -type d -name "docs" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules -type f \( -name "*.ts" -o -name "*.js.map" -o -name "*.d.ts" -o -name "*.d.ts.map" -o -name "LICENSE" -o -name "LICENSE.txt" -o -name "*.md" \) -delete && \
  find /usr/local/lib/node_modules/matterbridge/node_modules/@matter -type d -name "src" -exec rm -rf {} + && \
  find /usr/local/lib/node_modules/matterbridge/node_modules/@matter -type d -name "cjs" -exec rm -rf {} +

# Add Docker HEALTHCHECK
HEALTHCHECK --interval=60s --timeout=10s --start-period=60s --retries=5 \
  CMD curl --fail http://localhost:8283/health || exit 1

# Copy and execute the entrypoint script
COPY ./docker/entrypoint.debian.sh ./
RUN chmod +x ./entrypoint.debian.sh
ENTRYPOINT ["./entrypoint.debian.sh"]
CMD ["matterbridge", "-docker"]
# ─────────────── END ───────────────
