/**
 * Generated by scripts/data-model.mjs. Do not edit.
 *
 * @file matterNamespaces.ts
 * @remarks Matter data model version: 1.5.1
 */

export type MatterNamespaceTag = { id: number; name: string };
export type MatterNamespace = { id: number; name: string; tags: MatterNamespaceTag[] };
export type MatterNameSpaces = Record<string, MatterNamespace>;
export type MatterNamespaces = MatterNameSpaces;

export const MatterNamespaces = {
  CommonArea: {
    id: 16,
    name: 'Common Area',
    tags: [
      {
        id: 0,
        name: 'Aisle',
      },
      {
        id: 1,
        name: 'Attic',
      },
      {
        id: 2,
        name: 'BackDoor',
      },
      {
        id: 3,
        name: 'BackYard',
      },
      {
        id: 4,
        name: 'Balcony',
      },
      {
        id: 5,
        name: 'Ballroom',
      },
      {
        id: 6,
        name: 'Bathroom',
      },
      {
        id: 7,
        name: 'Bedroom',
      },
      {
        id: 8,
        name: 'Border',
      },
      {
        id: 9,
        name: 'Boxroom',
      },
      {
        id: 10,
        name: 'BreakfastRoom',
      },
      {
        id: 11,
        name: 'Carport',
      },
      {
        id: 12,
        name: 'Cellar',
      },
      {
        id: 13,
        name: 'Cloakroom',
      },
      {
        id: 14,
        name: 'Closet',
      },
      {
        id: 15,
        name: 'Conservatory',
      },
      {
        id: 16,
        name: 'Corridor',
      },
      {
        id: 17,
        name: 'CraftRoom',
      },
      {
        id: 18,
        name: 'Cupboard',
      },
      {
        id: 19,
        name: 'Deck',
      },
      {
        id: 20,
        name: 'Den',
      },
      {
        id: 21,
        name: 'Dining',
      },
      {
        id: 22,
        name: 'DrawingRoom',
      },
      {
        id: 23,
        name: 'DressingRoom',
      },
      {
        id: 24,
        name: 'Driveway',
      },
      {
        id: 25,
        name: 'Elevator',
      },
      {
        id: 26,
        name: 'Ensuite',
      },
      {
        id: 27,
        name: 'Entrance',
      },
      {
        id: 28,
        name: 'Entryway',
      },
      {
        id: 29,
        name: 'FamilyRoom',
      },
      {
        id: 30,
        name: 'Foyer',
      },
      {
        id: 31,
        name: 'FrontDoor',
      },
      {
        id: 32,
        name: 'FrontYard',
      },
      {
        id: 33,
        name: 'GameRoom',
      },
      {
        id: 34,
        name: 'Garage',
      },
      {
        id: 35,
        name: 'GarageDoor',
      },
      {
        id: 36,
        name: 'Garden',
      },
      {
        id: 37,
        name: 'GardenDoor',
      },
      {
        id: 38,
        name: 'GuestBathroom',
      },
      {
        id: 39,
        name: 'GuestBedroom',
      },
      {
        id: 41,
        name: 'GuestRoom',
      },
      {
        id: 42,
        name: 'Gym',
      },
      {
        id: 43,
        name: 'Hallway',
      },
      {
        id: 44,
        name: 'HearthRoom',
      },
      {
        id: 45,
        name: 'KidsRoom',
      },
      {
        id: 46,
        name: 'KidsBedroom',
      },
      {
        id: 47,
        name: 'Kitchen',
      },
      {
        id: 49,
        name: 'LaundryRoom',
      },
      {
        id: 50,
        name: 'Lawn',
      },
      {
        id: 51,
        name: 'Library',
      },
      {
        id: 52,
        name: 'LivingRoom',
      },
      {
        id: 53,
        name: 'Lounge',
      },
      {
        id: 54,
        name: 'MediaTvRoom',
      },
      {
        id: 55,
        name: 'MudRoom',
      },
      {
        id: 56,
        name: 'MusicRoom',
      },
      {
        id: 57,
        name: 'Nursery',
      },
      {
        id: 58,
        name: 'Office',
      },
      {
        id: 59,
        name: 'OutdoorKitchen',
      },
      {
        id: 60,
        name: 'Outside',
      },
      {
        id: 61,
        name: 'Pantry',
      },
      {
        id: 62,
        name: 'ParkingLot',
      },
      {
        id: 63,
        name: 'Parlor',
      },
      {
        id: 64,
        name: 'Patio',
      },
      {
        id: 65,
        name: 'PlayRoom',
      },
      {
        id: 66,
        name: 'PoolRoom',
      },
      {
        id: 67,
        name: 'Porch',
      },
      {
        id: 68,
        name: 'PrimaryBathroom',
      },
      {
        id: 69,
        name: 'PrimaryBedroom',
      },
      {
        id: 70,
        name: 'Ramp',
      },
      {
        id: 71,
        name: 'ReceptionRoom',
      },
      {
        id: 72,
        name: 'RecreationRoom',
      },
      {
        id: 74,
        name: 'Roof',
      },
      {
        id: 75,
        name: 'Sauna',
      },
      {
        id: 76,
        name: 'Scullery',
      },
      {
        id: 77,
        name: 'SewingRoom',
      },
      {
        id: 78,
        name: 'Shed',
      },
      {
        id: 79,
        name: 'SideDoor',
      },
      {
        id: 80,
        name: 'SideYard',
      },
      {
        id: 81,
        name: 'SittingRoom',
      },
      {
        id: 82,
        name: 'Snug',
      },
      {
        id: 83,
        name: 'Spa',
      },
      {
        id: 84,
        name: 'Staircase',
      },
      {
        id: 85,
        name: 'SteamRoom',
      },
      {
        id: 86,
        name: 'StorageRoom',
      },
      {
        id: 87,
        name: 'Studio',
      },
      {
        id: 88,
        name: 'Study',
      },
      {
        id: 89,
        name: 'SunRoom',
      },
      {
        id: 90,
        name: 'SwimmingPool',
      },
      {
        id: 91,
        name: 'Terrace',
      },
      {
        id: 92,
        name: 'UtilityRoom',
      },
      {
        id: 93,
        name: 'Ward',
      },
      {
        id: 94,
        name: 'Workshop',
      },
      {
        id: 95,
        name: 'Toilet',
      },
    ],
  },
  CommonClosure: {
    id: 1,
    name: 'Common Closure',
    tags: [
      {
        id: 0,
        name: 'Opening',
      },
      {
        id: 1,
        name: 'Closing',
      },
      {
        id: 2,
        name: 'Stop',
      },
    ],
  },
  CommonCompassDirection: {
    id: 2,
    name: 'Common Compass Direction',
    tags: [
      {
        id: 0,
        name: 'Northward',
      },
      {
        id: 1,
        name: 'NorthEastward',
      },
      {
        id: 2,
        name: 'Eastward',
      },
      {
        id: 3,
        name: 'SouthEastward',
      },
      {
        id: 4,
        name: 'Southward',
      },
      {
        id: 5,
        name: 'SouthWestward',
      },
      {
        id: 6,
        name: 'Westward',
      },
      {
        id: 7,
        name: 'NorthWestward',
      },
    ],
  },
  CommonCompassLocation: {
    id: 3,
    name: 'Common Compass Location',
    tags: [
      {
        id: 0,
        name: 'North',
      },
      {
        id: 1,
        name: 'NorthEast',
      },
      {
        id: 2,
        name: 'East',
      },
      {
        id: 3,
        name: 'SouthEast',
      },
      {
        id: 4,
        name: 'South',
      },
      {
        id: 5,
        name: 'SouthWest',
      },
      {
        id: 6,
        name: 'West',
      },
      {
        id: 7,
        name: 'NorthWest',
      },
    ],
  },
  CommonDirection: {
    id: 4,
    name: 'Common Direction',
    tags: [
      {
        id: 0,
        name: 'Upward',
      },
      {
        id: 1,
        name: 'Downward',
      },
      {
        id: 2,
        name: 'Leftward',
      },
      {
        id: 3,
        name: 'Rightward',
      },
      {
        id: 4,
        name: 'Forward',
      },
      {
        id: 5,
        name: 'Backward',
      },
    ],
  },
  CommonLandmark: {
    id: 17,
    name: 'Common Landmark',
    tags: [
      {
        id: 0,
        name: 'AirConditioner',
      },
      {
        id: 1,
        name: 'AirPurifier',
      },
      {
        id: 2,
        name: 'BackDoor',
      },
      {
        id: 3,
        name: 'BarStool',
      },
      {
        id: 4,
        name: 'BathMat',
      },
      {
        id: 5,
        name: 'Bathtub',
      },
      {
        id: 6,
        name: 'Bed',
      },
      {
        id: 7,
        name: 'Bookshelf',
      },
      {
        id: 8,
        name: 'Chair',
      },
      {
        id: 9,
        name: 'ChristmasTree',
      },
      {
        id: 10,
        name: 'CoatRack',
      },
      {
        id: 11,
        name: 'CoffeeTable',
      },
      {
        id: 12,
        name: 'CookingRange',
      },
      {
        id: 13,
        name: 'Couch',
      },
      {
        id: 14,
        name: 'Countertop',
      },
      {
        id: 15,
        name: 'Cradle',
      },
      {
        id: 16,
        name: 'Crib',
      },
      {
        id: 17,
        name: 'Desk',
      },
      {
        id: 18,
        name: 'DiningTable',
      },
      {
        id: 19,
        name: 'Dishwasher',
      },
      {
        id: 20,
        name: 'Door',
      },
      {
        id: 21,
        name: 'Dresser',
      },
      {
        id: 22,
        name: 'LaundryDryer',
      },
      {
        id: 23,
        name: 'Fan',
      },
      {
        id: 24,
        name: 'Fireplace',
      },
      {
        id: 25,
        name: 'Freezer',
      },
      {
        id: 26,
        name: 'FrontDoor',
      },
      {
        id: 27,
        name: 'HighChair',
      },
      {
        id: 28,
        name: 'KitchenIsland',
      },
      {
        id: 29,
        name: 'Lamp',
      },
      {
        id: 30,
        name: 'LitterBox',
      },
      {
        id: 31,
        name: 'Mirror',
      },
      {
        id: 32,
        name: 'Nightstand',
      },
      {
        id: 33,
        name: 'Oven',
      },
      {
        id: 34,
        name: 'PetBed',
      },
      {
        id: 35,
        name: 'PetBowl',
      },
      {
        id: 36,
        name: 'PetCrate',
      },
      {
        id: 37,
        name: 'Refrigerator',
      },
      {
        id: 38,
        name: 'ScratchingPost',
      },
      {
        id: 39,
        name: 'ShoeRack',
      },
      {
        id: 40,
        name: 'Shower',
      },
      {
        id: 41,
        name: 'SideDoor',
      },
      {
        id: 42,
        name: 'Sink',
      },
      {
        id: 43,
        name: 'Sofa',
      },
      {
        id: 44,
        name: 'Stove',
      },
      {
        id: 45,
        name: 'Table',
      },
      {
        id: 46,
        name: 'Toilet',
      },
      {
        id: 47,
        name: 'TrashCan',
      },
      {
        id: 48,
        name: 'LaundryWasher',
      },
      {
        id: 49,
        name: 'Window',
      },
      {
        id: 50,
        name: 'WineCooler',
      },
    ],
  },
  CommonLevel: {
    id: 5,
    name: 'Common Level',
    tags: [
      {
        id: 0,
        name: 'Low',
      },
      {
        id: 1,
        name: 'Medium',
      },
      {
        id: 2,
        name: 'High',
      },
    ],
  },
  CommonLocation: {
    id: 6,
    name: 'Common Location',
    tags: [
      {
        id: 0,
        name: 'Indoor',
      },
      {
        id: 1,
        name: 'Outdoor',
      },
      {
        id: 2,
        name: 'Inside',
      },
      {
        id: 3,
        name: 'Outside',
      },
      {
        id: 4,
        name: 'Zone',
      },
    ],
  },
  CommonNumber: {
    id: 7,
    name: 'Common Number',
    tags: [
      {
        id: 0,
        name: 'Zero',
      },
      {
        id: 1,
        name: 'One',
      },
      {
        id: 2,
        name: 'Two',
      },
      {
        id: 3,
        name: 'Three',
      },
      {
        id: 4,
        name: 'Four',
      },
      {
        id: 5,
        name: 'Five',
      },
      {
        id: 6,
        name: 'Six',
      },
      {
        id: 7,
        name: 'Seven',
      },
      {
        id: 8,
        name: 'Eight',
      },
      {
        id: 9,
        name: 'Nine',
      },
      {
        id: 10,
        name: 'Ten',
      },
      {
        id: 11,
        name: 'Eleven',
      },
      {
        id: 12,
        name: 'Twelve',
      },
      {
        id: 13,
        name: 'Thirteen',
      },
      {
        id: 14,
        name: 'Fourteen',
      },
      {
        id: 15,
        name: 'Fifteen',
      },
      {
        id: 16,
        name: 'Sixteen',
      },
      {
        id: 17,
        name: 'Seventeen',
      },
      {
        id: 18,
        name: 'Eighteen',
      },
      {
        id: 19,
        name: 'Nineteen',
      },
      {
        id: 20,
        name: 'Twenty',
      },
      {
        id: 21,
        name: 'TwentyOne',
      },
      {
        id: 22,
        name: 'TwentyTwo',
      },
      {
        id: 23,
        name: 'TwentyThree',
      },
      {
        id: 24,
        name: 'TwentyFour',
      },
      {
        id: 25,
        name: 'TwentyFive',
      },
      {
        id: 26,
        name: 'TwentySix',
      },
      {
        id: 27,
        name: 'TwentySeven',
      },
      {
        id: 28,
        name: 'TwentyEight',
      },
      {
        id: 29,
        name: 'TwentyNine',
      },
      {
        id: 30,
        name: 'Thirty',
      },
    ],
  },
  CommonPosition: {
    id: 8,
    name: 'Common Position',
    tags: [
      {
        id: 0,
        name: 'Left',
      },
      {
        id: 1,
        name: 'Right',
      },
      {
        id: 2,
        name: 'Top',
      },
      {
        id: 3,
        name: 'Bottom',
      },
      {
        id: 4,
        name: 'Middle',
      },
      {
        id: 5,
        name: 'Row',
      },
      {
        id: 6,
        name: 'Column',
      },
    ],
  },
  CommonRelativePosition: {
    id: 18,
    name: 'Common Relative Position',
    tags: [
      {
        id: 0,
        name: 'Under',
      },
      {
        id: 1,
        name: 'NextTo',
      },
      {
        id: 2,
        name: 'Around',
      },
      {
        id: 3,
        name: 'On',
      },
      {
        id: 4,
        name: 'Above',
      },
      {
        id: 5,
        name: 'FrontOf',
      },
      {
        id: 6,
        name: 'Behind',
      },
    ],
  },
  ElectricalMeasurement: {
    id: 10,
    name: 'Electrical Measurement',
    tags: [
      {
        id: 0,
        name: 'DC',
      },
      {
        id: 1,
        name: 'AC',
      },
      {
        id: 2,
        name: 'ACPhase1',
      },
      {
        id: 3,
        name: 'ACPhase2',
      },
      {
        id: 4,
        name: 'ACPhase3',
      },
    ],
  },
  Laundry: {
    id: 14,
    name: 'Laundry',
    tags: [
      {
        id: 0,
        name: 'Normal',
      },
      {
        id: 1,
        name: 'LightDry',
      },
      {
        id: 2,
        name: 'ExtraDry',
      },
      {
        id: 3,
        name: 'NoDry',
      },
    ],
  },
  PowerSource: {
    id: 15,
    name: 'Power Source',
    tags: [
      {
        id: 0,
        name: 'Unknown',
      },
      {
        id: 1,
        name: 'Grid',
      },
      {
        id: 2,
        name: 'Solar',
      },
      {
        id: 3,
        name: 'Battery',
      },
      {
        id: 4,
        name: 'EV',
      },
    ],
  },
  Refrigerator: {
    id: 65,
    name: 'Refrigerator',
    tags: [
      {
        id: 0,
        name: 'Refrigerator',
      },
      {
        id: 1,
        name: 'Freezer',
      },
    ],
  },
  RoomAirConditioner: {
    id: 66,
    name: 'Room Air Conditioner',
    tags: [
      {
        id: 0,
        name: 'Evaporator',
      },
      {
        id: 1,
        name: 'Condenser',
      },
    ],
  },
  Switches: {
    id: 67,
    name: 'Switches',
    tags: [
      {
        id: 0,
        name: 'On',
      },
      {
        id: 1,
        name: 'Off',
      },
      {
        id: 2,
        name: 'Toggle',
      },
      {
        id: 3,
        name: 'Up',
      },
      {
        id: 4,
        name: 'Down',
      },
      {
        id: 5,
        name: 'Next',
      },
      {
        id: 6,
        name: 'Previous',
      },
      {
        id: 7,
        name: 'EnterOkSelect',
      },
      {
        id: 8,
        name: 'Custom',
      },
      {
        id: 9,
        name: 'Open',
      },
      {
        id: 10,
        name: 'Close',
      },
      {
        id: 11,
        name: 'Stop',
      },
    ],
  },
} satisfies MatterNameSpaces;
