title: Matterbridge
description: >-
  Matterbridge is a Matter plugin manager that allows you to have all your 
  Matter devices up and running in minutes without dealing with complex pairing processes.

baseurl: '/matterbridge'
url: 'https://luligu.github.io'

author:
  name: Luligu
  email:
  github: Luligu

repository: Luligu/matterbridge

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# GitHub Pages specific settings
github:
  repository_url: https://github.com/Luligu/matterbridge

# Default front matter
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

social:
  name: Matterbridge
  links:
    - https://github.com/Luligu/matterbridge
    - https://www.npmjs.com/package/matterbridge
    - https://hub.docker.com/r/luligu/matterbridge

# Logo and favicon
logo: matterbridge.svg
