name: Node.js CI

on:
  push:
    branches: [main, dev]
    paths:
      - 'frontend/**' # any file under frontend
  pull_request:
    branches: [main, dev]
    paths:
      - 'frontend/**' # any file under frontend
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Clean cache
        run: npm cache clean --force
        working-directory: frontend

      - name: Verify Node.js version
        run: node -v
        working-directory: frontend

      - name: Verify Npm version
        run: npm -v
        working-directory: frontend

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Lint the project
        run: npm run lint
        working-directory: frontend

      - name: Build the project
        run: npm run build
        working-directory: frontend

      - name: Test the project
        run: npm run test
        working-directory: frontend

      - name: List, audit, fix outdated dependencies, update and build again
        run: |
          npm outdated || true
          npm audit || true
          npm audit fix || true
          npm update || true
          npm run lint || true
          npm run build
        working-directory: frontend
